all:
  children:
    api_server:
      hosts:
        ms-server:
          ansible_user: <server_username>
          lan_ip: <server_ip>

    kiosks:
      hosts:
        ms-kiosk-1:
          ansible_user: <kiosk_username>
          lan_ip: <kiosk_1_ip>
          has_barcode_scanner: true
          has_traffic_light: true
          allows_registration: true
        ms-kiosk-2:
          ansible_user: <kiosk_username>
          lan_ip: <kiosk_2_ip>
          has_barcode_scanner: false
          has_traffic_light: false
          allows_registration: false
