all:
  children:
    api_server:
      hosts:
        ms-server:
          ansible_user: makeradmin
          lan_ip: 192.168.1.106

    kiosks:
      hosts:
        ms-kiosk-1:
          ansible_user: makeradmin
          lan_ip: 192.168.1.241
          has_barcode_scanner: false
          has_traffic_light: true
          allows_registration: true
        ms-kiosk-2:
          ansible_user: makeradmin
          lan_ip: 192.168.1.84
          has_barcode_scanner: false
          has_traffic_light: false
          allows_registration: false
